package com.stakater.nordmart;

import com.fasterxml.jackson.databind.ObjectMapper;
import feign.RequestInterceptor;
import feign.RequestTemplate;
import java.io.IOException;
import java.util.HashMap;

import io.jaegertracing.Configuration;
import io.opentracing.Tracer;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.feign.EnableFeignClients;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
@EnableFeignClients
public class CartServiceApplication
{
    @Bean
    public Tracer jaegerTracer() {
        // The following environment variables need to set
        // JAEGER_ENDPOINT="http://10.42.126.171:28019/api/traces"
        // JAEGER_PROPAGATION="b3"
        // JAEGER_TRACEID_128BIT="true" Use 128bit tracer id to be compatible with the
        // trace id generated by istio/envoy
        return Configuration.fromEnv("nordmart-cart-opentracing").getTracer();
    }

    public static void main(String[] args)
    {
        SpringApplication.run(CartServiceApplication.class, args);
    }

    @Bean
    public RequestInterceptor requestTokenBearerInterceptor()
    {

        return new RequestInterceptor()
        {
            @Override
            public void apply(RequestTemplate requestTemplate)
            {
                try
                {
                    HashMap result = new ObjectMapper().readValue(requestTemplate.body(), HashMap.class);

                    result.forEach((key, value) -> {
                        requestTemplate.header(key.toString(), value.toString());
                    });
                    requestTemplate.body(null);
                } catch (IOException e)
                {
                    e.printStackTrace();
                }

            }
        };
    }
}
