application:
  applicationName: "cart"
  deployment:
    additionalLabels:
      appCategory: "backend"
    annotations:
    resources: 
      limits:
         memory: 1Gi
         cpu: 0.5
      requests:
        memory: 128Mi
        cpu: 0.1
    imagePullSecrets: nexus-docker-config-forked
    image:
      repository: stakater/stakater-nordmart-cart
      tag: v0.0.2
    volumes: {}
    # Resources to be defined for pod
    resources: 
      limits:
        memory: 512Mi
        cpu: 0.5
      requests:
        memory: 128Mi
        cpu: 0.1    
    envFrom:
    - type: configmap
    probes:
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 150
        httpGet:
          path: /health
          port: 8080
      livenessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 150
        httpGet:
          path: /health
          port: 8080          
  service:
    ports:
    - port: 8080
      name: https
      targetPort: 8080
  rbac:
    create: true
    serviceAccount:
      enabled: true
      create: true
  configMap:
    enabled: true
    data:
      CATALOG_ENDPOINT: "catalog:8080"
      KEYCLOAK_REALM: "nordmart"
      KEYCLOAK_URL: "https://keycloak-NAMESPACE.DOMAIN/auth/"
      KEYCLOAK_CLIENT_BACKEND: "stakater-nordmart-backend"
      KEYCLOAK_CLIENT_SECRET_KEY: "7672aea2-81ff-4aa2-affe-daf3bad10334"
      JAEGER_ENDPOINT: "http://jaeger-collector.istio-system:14268/api/traces"
