application:
  applicationName: "cart"
  deployment:
    additionalLabels:
      appCategory: "backend"
    annotations:
    imagePullSecrets: nexus-creds
    image:
      repository: stakater/stakater-nordmart-cart
      tag: v0.0.2
    volumes: {}
    env:
    - name: CATALOG_ENDPOINT
      value: "catalog:8080"
    - name: KEYCLOAK_REALM
      value: "nordmart"
    - name: KEYCLOAK_URL
      value: "https://keycloak-NAMESPACE.DOMAIN/auth/"
    - name: KEYCLOAK_CLIENT_BACKEND
      value: "stakater-nordmart-backend"
    - name: KEYCLOAK_CLIENT_SECRET_KEY
      value: "7672aea2-81ff-4aa2-affe-daf3bad10334"
    - name: JAEGER_ENDPOINT
      value: "http://jaeger-collector.istio-system:14268/api/traces"
    probes:
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 150
        httpGet:
          path: /health
          port: 8080
      livenessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 150
        httpGet:
          path: /health
          port: 8080
  service:
    ports:
    - port: 8080
      name: https
      targetPort: 8080
  rbac:
    create: true
    serviceAccount:
      enabled: true
      create: true
  configMap:
    enabled: false
  # Resources to be defined for pod
  resources: 
    limits:
      memory: 512Mi
      cpu: 0.5
    requests:
      memory: 128Mi
      cpu: 0.1
