apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 0.0.1
  name: cart
  namespace: {NAMESPACE}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cart
    spec:
      imagePullSecrets:
      - name: docker-nexus-registry-secret
      containers:
      - name: cart
        image: "{IMAGE}"
        env:
        - name: CATALOG_ENDPOINT
          value: "catalog.coolstore:8080"
        ports:
        - containerPort: 8080